name: Android CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build & Notify
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

#      - name: Build Release APK
#        run: ./gradlew assembleRelease --stacktrace

      - name: Telegram Success
        if: ${{ success() }}
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument" \
            -F chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -F document=@"${GITHUB_WORKSPACE}/app/build/outputs/apk/debug/app-debug.apk" \
            -F caption="Все прошло супер, вот дебаг версия 🥵🥵🥵"
#          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument" \
#            -F chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
#            -F document=@"${GITHUB_WORKSPACE}/app/build/outputs/apk/release/app-release-unsigned.apk" \
#            -F caption="Все прошло супер, вот релиз версия 🤯🤯🤯"

      - name: Telegram Failure
        if: ${{ failure() }}
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d text="Все прошло неудачно🤬🤬🤬"
