name: Android CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build & Notify
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

#      - name: Build Release APK
#        run: ./gradlew assembleRelease --stacktrace

      - name: Telegram Success
        if: ${{ success() }}
        run: |
          messages=(
            "Вечерок в хату, тут обнова подъехала"
            "Сборка взлетела, как ракета в космос"
            "CI миновал бурю и доставил APK целым"
            "Обновление на районе — качаем, не тормозим"
            "Релиз готов, баги сдаём без потерь"
            "Апдейт прошёл, как по маслу"
            "Код в продакшен отправлен — праздник удался"
            "Debug-версия чёткая, как утренний кофе"
            "Сборка идеальная, даже линтер в шоке"
            "APK выехал на трассу, едем без пробок"
            "CI-джигит укротил тесты и собрал билд"
            "Новый билд на старте — разгоняемся!"
            "Баги схлопнулись, релиз сияет"
            "Пуш в main — врываемся с апдейтом"
            "Сервер одобрил, мы выкатываем новинку"
            "APK в телегу ушёл — поздравляем команду"
            "Сборка прокачена и готова к испытаниям"
            "Все тесты в шоке от скоростного прохождения"
            "Проект обновлён — мир спасён"
            "Наша сборка — как новогодняя ёлка: сияет"
            "Версия горячая, как пельмени"
          )
          idx=$(( RANDOM % ${#messages[@]} ))
          random_msg="${messages[$idx]}"

          if [ "${{ github.event_name }}" = "pull_request" ]; then
            COMMENT="${{ github.event.pull_request.title }}"
          else
            COMMENT="${{ github.event.head_commit.message }}"
          fi

          caption="✅ $random_msg\n\nВот новая дебаг-версия.\nКомментарий: *$COMMENT*"

          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument" \
            -F chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -F document=@"${GITHUB_WORKSPACE}/app/build/outputs/apk/debug/app-debug.apk" \
            -F caption="$caption" \
            -F parse_mode=Markdown

      #          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument" \
#            -F chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
#            -F document=@"${GITHUB_WORKSPACE}/app/build/outputs/apk/release/app-release-unsigned.apk" \
#            -F caption="Все прошло супер, вот релиз версия 🤯🤯🤯"

      - name: Telegram Failure
        if: ${{ failure() }}
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -d text="Упс, что-то поломалось, так что пока новой версии не будет 🤬🤬🤬"
